In [25]:
## Import block
%matplotlib inline

import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

import numpy as np
from numpy import linalg as LA
import pandas as pd

import random 

from sklearn.svm import SVC
from sklearn.datasets import make_circles

# Part 2: SVM for Malware Detection

The following code applies an SVM algorithm to 

In [26]:
# Import dataset
files = pd.read_csv("dataset_malwares.csv")

In [27]:
print(files.head())

                                          Name  e_magic  e_cblp  e_cp  e_crlc  \
0  VirusShare_a878ba26000edaac5c98eff4432723b3    23117     144     3       0   
1  VirusShare_ef9130570fddc174b312b2047f5f4cf0    23117     144     3       0   
2  VirusShare_ef84cdeba22be72a69b198213dada81a    23117     144     3       0   
3  VirusShare_6bf3608e60ebc16cbcff6ed5467d469e    23117     144     3       0   
4  VirusShare_2cc94d952b2efb13c7d6bbe0dd59d3fb    23117     144     3       0   

   e_cparhdr  e_minalloc  e_maxalloc  e_ss  e_sp  ...  SectionMaxChar  \
0          4           0       65535     0   184  ...      3758096608   
1          4           0       65535     0   184  ...      3791650880   
2          4           0       65535     0   184  ...      3221225536   
3          4           0       65535     0   184  ...      3224371328   
4          4           0       65535     0   184  ...      3227516992   

   SectionMainChar  DirectoryEntryImport  DirectoryEntryImportSize  \
0   

In [28]:
malware = files['Malware']
files = files.drop(columns=['Malware'])
files.insert(loc=78, column='Malware', value=malware)

files_np = np.array(files)
files_np = files_np[:, 2:].astype('float')
sample_index = random.sample(range(len(files_np)), 100)
sample = files_np[sample_index, :]

In [30]:
files.head()

Name  e_magic  e_cblp  e_cp  e_crlc  \
0  VirusShare_a878ba26000edaac5c98eff4432723b3    23117     144     3       0   
1  VirusShare_ef9130570fddc174b312b2047f5f4cf0    23117     144     3       0   
2  VirusShare_ef84cdeba22be72a69b198213dada81a    23117     144     3       0   
3  VirusShare_6bf3608e60ebc16cbcff6ed5467d469e    23117     144     3       0   
4  VirusShare_2cc94d952b2efb13c7d6bbe0dd59d3fb    23117     144     3       0   

   e_cparhdr  e_minalloc  e_maxalloc  e_ss  e_sp  ...  SectionMainChar  \
0          4           0       65535     0   184  ...                0   
1          4           0       65535     0   184  ...                0   
2          4           0       65535     0   184  ...                0   
3          4           0       65535     0   184  ...                0   
4          4           0       65535     0   184  ...                0   

   DirectoryEntryImport  DirectoryEntryImportSize  DirectoryEntryExport  \
0                     7                       152                     0   
1                    16                       311                     0   
2                     6                       176                     0   
3                     8                       155                     0   
4                     2                        43                     0   

   ImageDirectoryEntryExport  ImageDirectoryEntryImport  \
0                          0                      54440   
1                          0                     262276   
2                          0                      36864   
3                          0                     356352   
4                          0                      61440   

   ImageDirectoryEntryResource  ImageDirectoryEntryException  \
0                        77824                         73728   
1                       294912                             0   
2                        40960                             0   
3                      1003520                             0   
4                        73728                             0   

   ImageDirectoryEntrySecurity  Malware  
0                            0        1  
1                       346112        1  
2                            0        1  
3                     14109472        1  
4                        90624        1  

[5 rows x 79 columns]

In [31]:
# checking that we have both classes present in the sample
np.sum(sample[:, -1])

77.0

In [23]:
svm = SVC(kernel="rbf", C=1E6)


In [32]:
svm.fit(sample[:, :-1], sample[:, -1])

SVC(C=1000000.0)

In [33]:
print(svm.predict(files_np[:10, :-1]))
print(files_np[:10, -1])

[1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
print(svm.predict(emails_np[12:20, :-1]))
print(emails_np[12:20, -1])

[0 0 0 0 0 0 0 0]
[0 0 0 0 1 1 0 0]
